import Link from "next/link";
import { notFound } from "next/navigation";
import AffiliateDisclosure from "../../../components/AffiliateDisclosure";
import ProductCard from "../../../components/ProductCard";
import { products, getProduct } from "../../../lib/catalog";
export function generateStaticParams(){ return products.map(p=>({slug:p.slug})); }
export async function generateMetadata({params}){ const {slug}=await params; const p=getProduct(slug); if(!p)return {}; return {title:`${p.title}: What to Look For`,description:`Paw Nova's practical notes on choosing a ${p.title.toLowerCase()} for ${p.useCase}.`,alternates:{canonical:`/products/${p.slug}`},openGraph:{title:`${p.title} | Paw Nova`,description:p.summary,url:`https://pawnovaco.com/products/${p.slug}`}}; }
export default async function ProductPage({params}){ const {slug}=await params; const p=getProduct(slug); if(!p)notFound(); const related=products.filter(x=>x.category===p.category&&x.slug!==p.slug).slice(0,3); const schema={"@context":"https://schema.org","@type":"Article",headline:`${p.title}: Paw Nova buying notes`,description:p.summary,author:{"@type":"Organization",name:"Paw Nova"},publisher:{"@type":"Organization",name:"Paw Nova"},dateModified:p.updated,mainEntityOfPage:`https://pawnovaco.com/products/${p.slug}`}; return <>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
<section className="page-hero"><div className="container narrow"><span className="eyebrow">{p.categoryLabel}</span><h1>{p.title}</h1><p>{p.summary}</p><AffiliateDisclosure compact/></div></section>
<section className="section"><div className="container product-detail-grid"><article className="editorial-card"><h2>Why it can be useful</h2><p>For dog owners dealing with <strong>{p.useCase}</strong>, this type of product can be worth comparing. Paw Nova focuses on the job a product needs to do rather than treating a bestseller badge as a recommendation.</p><h2>Best for</h2><p>{p.bestFor}</p><h2>What to check before buying</h2><p>{p.watchFor}</p><div className="info-box"><strong>Recommendation status</strong><p>{p.amazonUrl ? "We have added a verified Amazon destination for this recommendation." : "We are still verifying the specific Amazon listing we want to recommend. We do not publish an affiliate button until the destination has been reviewed."}</p></div>{p.amazonUrl ? <a className="button" href={p.amazonUrl} target="_blank" rel="sponsored nofollow noopener">View on Amazon (paid link)</a>:null}</article><aside className="editorial-card"><h2>Quick checklist</h2><ul className="check-list"><li>Correct size for your dog</li><li>Materials and cleaning instructions</li><li>Safety considerations for the intended use</li><li>Recent product details on the seller page</li><li>Whether a simpler product solves the same problem</li></ul><Link href={`/${p.category}`} className="text-link">Browse {p.categoryLabel} →</Link></aside></div></section>
<section className="section section-soft"><div className="container"><div className="section-heading"><div><span className="eyebrow">Related</span><h2>More {p.categoryLabel.toLowerCase()} ideas</h2></div></div><div className="cards-grid">{related.map(x=><ProductCard key={x.slug} product={x}/>)}</div></div></section></>; }
